=== folio-org/mod-rtac-cache/src/main/resources/swagger.api/schemas/kafka/circulationResourceEvent.json
{
  "type": "object",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Circulation event body",
  "properties": {
    "id": {
      "description": "Event id",
      "type": "string"
    },
    "type": {
      "description": "Event type",
      "$ref": "circulationEventType.json"
    },
    "tenant": {
      "description": "Tenant id",
      "type": "string"
    },
    "timestamp": {
      "description": "Event timestamp",
      "type": "integer",
      "format": "int64"
    },
    "data": {
      "description": "Event data",
      "type": "object",
      "properties": {
        "new": {
          "description": "Record new fields",
          "type": "object"
        },
        "old": {
          "description": "Record old fields",
          "type": "object"
        }
      }
    }
  }
}

=== folio-org/mod-rtac-cache/src/test/resources/__files/kafka-events/update-request-event.json
{
  "id": "e1fd6ce1-8908-4d9a-aef5-c66300c613a1",
  "type": "UPDATED",
  "tenant": "testTenant",
  "timestamp": 1762973441588,
  "data": {
    "old": {
      "id": "2a93ae85-d82b-437a-8e9d-69232f6cd0f9",
      "requestLevel": "Item",
      "requestType": "Page",
      "requestDate": "2024-05-29T11:57:39.452+00:00",
      "requesterId": "d5e9c535-ff27-4937-9875-c9ff71404fe0",
      "instanceId": "843b368d-411c-4dce-bd64-99afc53f508d",
      "holdingsRecordId": "55fa3746-8176-49c5-9809-b29dd7bb9b47",
      "itemId": "522d41d3-0e04-416d-9f52-90ac67685a78",
      "status": "Open - Not yet filled",
      "position": 1,
      "instance": {
        "title": "Annuals.",
        "identifiers": [
          {
            "value": "88002308",
            "identifierTypeId": "c858e4f2-2b6b-4385-842b-60732ee14abb"
          },
          {
            "value": "0809466120",
            "identifierTypeId": "8261054f-be78-422d-bd51-4ed9f33c3422"
          },
          {
            "value": "0809466139 (lib. bdg.)",
            "identifierTypeId": "8261054f-be78-422d-bd51-4ed9f33c3422"
          },
          {
            "value": "TRUMANBAD2070",
            "identifierTypeId": "7e591197-f335-4afb-bc6d-a6d76ca3bace"
          },
          {
            "value": ".b13416650MOBNE",
            "identifierTypeId": "7e591197-f335-4afb-bc6d-a6d76ca3bace"
          },
          {
            "value": "17649206",
            "identifierTypeId": "7e591197-f335-4afb-bc6d-a6d76ca3bace"
          }
        ]
      },
      "item": {
        "barcode": "1232323232"
      },
      "requester": {
        "firstName": "EBSCOFseAdmin",
        "lastName": "EBSCOFseAdmin"
      },
      "fulfillmentPreference": "Hold Shelf",
      "pickupServicePointId": "9d1b77e8-f02e-4b7f-b296-3f2042ddac54",
      "metadata": {
        "createdDate": "2024-05-29T11:57:41.321+00:00",
        "createdByUserId": "daaf98f2-4d8b-4ebf-b473-31f8c449fdc2",
        "updatedDate": "2024-05-29T11:57:41.349+00:00",
        "updatedByUserId": "daaf98f2-4d8b-4ebf-b473-31f8c449fdc2"
      },
      "searchIndex": {
        "callNumberComponents": {
          "callNumber": "SB422"
        },
        "shelvingOrder": "SB422",
        "pickupServicePointName": "DCB"
      }
    },
    "new": {
      "id": "2a93ae85-d82b-437a-8e9d-69232f6cd0f9",
      "requestLevel": "Item",
      "requestType": "Page",
      "requestDate": "2024-05-29T11:57:39.452+00:00",
      "requesterId": "d5e9c535-ff27-4937-9875-c9ff71404fe0",
      "instanceId": "843b368d-411c-4dce-bd64-99afc53f508d",
      "holdingsRecordId": "55fa3746-8176-49c5-9809-b29dd7bb9b47",
      "itemId": "522d41d3-0e04-416d-9f52-90ac67685a78",
      "status": "Closed - Cancelled",
      "cancellationReasonId": "50ed35b2-1397-4e83-a76b-642adf91ca2a",
      "cancelledByUserId": "daaf98f2-4d8b-4ebf-b473-31f8c449fdc2",
      "cancellationAdditionalInformation": "cancell",
      "cancelledDate": "2025-11-12T18:50:37.313+00:00",
      "instance": {
        "title": "Annuals.",
        "identifiers": [
          {
            "value": "88002308",
            "identifierTypeId": "c858e4f2-2b6b-4385-842b-60732ee14abb"
          },
          {
            "value": "0809466120",
            "identifierTypeId": "8261054f-be78-422d-bd51-4ed9f33c3422"
          },
          {
            "value": "0809466139 (lib. bdg.)",
            "identifierTypeId": "8261054f-be78-422d-bd51-4ed9f33c3422"
          },
          {
            "value": "TRUMANBAD2070",
            "identifierTypeId": "7e591197-f335-4afb-bc6d-a6d76ca3bace"
          },
          {
            "value": ".b13416650MOBNE",
            "identifierTypeId": "7e591197-f335-4afb-bc6d-a6d76ca3bace"
          },
          {
            "value": "17649206",
            "identifierTypeId": "7e591197-f335-4afb-bc6d-a6d76ca3bace"
          }
        ]
      },
      "item": {
        "barcode": "1232323232",
        "itemEffectiveLocationId": "108ef496-ef5b-421b-baa9-109833493599",
        "itemEffectiveLocationName": "Comic Collection",
        "retrievalServicePointId": "650b2d28-dc05-4177-9dc3-c45316fe5aa6",
        "retrievalServicePointName": "Main circ college"
      },
      "requester": {
        "firstName": "EBSCOFseAdmin",
        "lastName": "EBSCOFseAdmin",
        "barcode": "555555"
      },
      "fulfillmentPreference": "Hold Shelf",
      "pickupServicePointId": "9d1b77e8-f02e-4b7f-b296-3f2042ddac54",
      "metadata": {
        "createdDate": "2024-05-29T11:57:41.321+00:00",
        "createdByUserId": "daaf98f2-4d8b-4ebf-b473-31f8c449fdc2",
        "updatedDate": "2025-11-12T18:50:41.533+00:00",
        "updatedByUserId": "daaf98f2-4d8b-4ebf-b473-31f8c449fdc2"
      },
      "searchIndex": {
        "callNumberComponents": {
          "callNumber": "SB422"
        },
        "shelvingOrder": "SB422",
        "pickupServicePointName": "DCB"
      }
    }
  }
}

=== folio-org/mod-rtac-cache/src/test/resources/__files/kafka-events/create-loan-event.json
{
  "id": "6ef5a359-e1b8-464b-9449-a14506767a02",
  "type": "CREATED",
  "tenant": "testTenant",
  "timestamp": 1763033285660,
  "data": {
    "new": {
      "id": "ba86bc5a-980c-4af6-86ed-109dd7b4aee2",
      "userId": "d5e9c535-ff27-4937-9875-c9ff71404fe0",
      "itemId": "522d41d3-0e04-416d-9f52-90ac67685a78",
      "itemEffectiveLocationIdAtCheckOut": "108ef496-ef5b-421b-baa9-109833493599",
      "status": {
        "name": "Open"
      },
      "loanDate": "2025-11-13T11:28:03.559Z",
      "dueDate": "2026-01-12T23:59:59.000+00:00",
      "action": "checkedout",
      "itemStatus": "Checked out",
      "loanPolicyId": "d9cd0bed-1b49-4b5e-a7bd-064b8d177231",
      "checkoutServicePointId": "9d1b77e8-f02e-4b7f-b296-3f2042ddac54",
      "patronGroupIdAtCheckout": "cf07505c-f083-4388-9774-403247317015",
      "isDcb": false,
      "overdueFinePolicyId": "cd3f6cac-fa17-4079-9fae-2fb28e521412",
      "lostItemPolicyId": "9688df8d-a713-4b9f-a174-c16257fd41a2",
      "metadata": {
        "createdDate": "2025-11-13T11:28:05.596+00:00",
        "createdByUserId": "daaf98f2-4d8b-4ebf-b473-31f8c449fdc2",
        "updatedDate": "2025-11-13T11:28:05.596+00:00",
        "updatedByUserId": "daaf98f2-4d8b-4ebf-b473-31f8c449fdc2"
      }
    }
  }
}

=== folio-org/mod-rtac-cache/src/test/resources/__files/kafka-events/create-request-event.json
{
  "id": "68f5f282-43d2-4f37-bf1f-3f813abfdd09",
  "type": "CREATED",
  "tenant": "testTenant",
  "timestamp": 1762973817511,
  "data": {
    "new": {
      "id": "ff1a21fb-ae27-4aaf-acf6-b405dc4eed89",
      "requestLevel": "Item",
      "requestType": "Page",
      "requestDate": "2025-11-12T18:56:53.619+00:00",
      "requesterId": "d5e9c535-ff27-4937-9875-c9ff71404fe0",
      "instanceId": "843b368d-411c-4dce-bd64-99afc53f508d",
      "holdingsRecordId": "55fa3746-8176-49c5-9809-b29dd7bb9b47",
      "itemId": "522d41d3-0e04-416d-9f52-90ac67685a78",
      "status": "Open - Not yet filled",
      "instance": {
        "title": "\"Boss\" Tweed : the story of a grim generation / Denis Tilden Lynch.",
        "identifiers": [
          {
            "value": "73019157",
            "identifierTypeId": "c858e4f2-2b6b-4385-842b-60732ee14abb"
          },
          {
            "value": "0405058799 : $23.00",
            "identifierTypeId": "8261054f-be78-422d-bd51-4ed9f33c3422"
          },
          {
            "value": "0405058799",
            "identifierTypeId": "8261054f-be78-422d-bd51-4ed9f33c3422"
          },
          {
            "value": "MSSCAAN2494",
            "identifierTypeId": "7e591197-f335-4afb-bc6d-a6d76ca3bace"
          },
          {
            "value": "TRUMANAAF9326",
            "identifierTypeId": "7e591197-f335-4afb-bc6d-a6d76ca3bace"
          },
          {
            "value": ".b12064300MOBNE",
            "identifierTypeId": "7e591197-f335-4afb-bc6d-a6d76ca3bace"
          },
          {
            "value": "810354",
            "identifierTypeId": "7e591197-f335-4afb-bc6d-a6d76ca3bace"
          }
        ]
      },
      "item": {
        "barcode": "1232323232",
        "itemEffectiveLocationId": "773e5ce3-c226-4818-a78d-4de7ee0c9418",
        "itemEffectiveLocationName": "Special Collections",
        "retrievalServicePointId": "650b2d28-dc05-4177-9dc3-c45316fe5aa6",
        "retrievalServicePointName": "Main circ college"
      },
      "requester": {
        "firstName": "EBSCOFseAdmin",
        "lastName": "EBSCOFseAdmin",
        "barcode": "555555"
      },
      "fulfillmentPreference": "Hold Shelf",
      "pickupServicePointId": "be6cdc85-1202-4c48-99fa-56af591f5a3a",
      "metadata": {
        "createdDate": "2025-11-12T18:56:57.499+00:00",
        "createdByUserId": "daaf98f2-4d8b-4ebf-b473-31f8c449fdc2",
        "updatedDate": "2025-11-12T18:56:57.499+00:00",
        "updatedByUserId": "daaf98f2-4d8b-4ebf-b473-31f8c449fdc2"
      },
      "searchIndex": {
        "callNumberComponents": {
          "callNumber": "320.9/747/103"
        },
        "shelvingOrder": "3320.9 3747 3103",
        "pickupServicePointName": "Application"
      }
    }
  }
}
