=== folio-org/mod-rtac-cache/src/main/resources/swagger.api/schemas/kafka/inventoryResourceEvent.json
{
  "type": "object",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Inventory event body",
  "properties": {
    "eventId": {
      "description": "Event id",
      "type": "string"
    },
    "type": {
      "description": "Event type",
      "$ref": "inventoryEventType.json"
    },
    "tenant": {
      "description": "Tenant id",
      "type": "string"
    },
    "eventTs": {
      "description": "Event timestamp",
      "type": "integer",
      "format": "int64"
    },
    "new": {
      "description": "Record new fields",
      "type": "object"
    },
    "old": {
      "description": "Record old fields",
      "type": "object"
    }
  }
}

=== folio-org/mod-rtac-cache/src/test/resources/__files/kafka-events/update-location-event.json
{
  "old": {
    "id": "1c54d084-4639-45dd-b9c9-4473df6bd28a",
    "name": "Old location name",
    "code": "Old location code",
    "discoveryDisplayName": "Old location name",
    "isActive": true,
    "institutionId": "6ecd8132-caef-4f87-bbb0-9fc07d71357d",
    "campusId": "3cb95a54-1aac-47f2-9f97-c2b54a01bbfe",
    "libraryId": "79f1cd00-09cc-4c9c-99c1-d8ad1b77d128",
    "details": {},
    "primaryServicePoint": "be6cdc85-1202-4c48-99fa-56af591f5a3a",
    "servicePointIds": [
      "be6cdc85-1202-4c48-99fa-56af591f5a3a"
    ],
    "servicePoints": [],
    "metadata": {
      "createdDate": "2025-11-26T22:47:07.060+00:00",
      "createdByUserId": "daaf98f2-4d8b-4ebf-b473-31f8c449fdc2",
      "updatedDate": "2025-11-26T22:47:07.060+00:00",
      "updatedByUserId": "daaf98f2-4d8b-4ebf-b473-31f8c449fdc2"
    }
  },
  "new": {
    "id": "1c54d084-4639-45dd-b9c9-4473df6bd28a",
    "name": "New location name",
    "code": "New location code",
    "discoveryDisplayName": "New location name",
    "isActive": true,
    "institutionId": "6ecd8132-caef-4f87-bbb0-9fc07d71357d",
    "campusId": "3cb95a54-1aac-47f2-9f97-c2b54a01bbfe",
    "libraryId": "79f1cd00-09cc-4c9c-99c1-d8ad1b77d128",
    "details": {},
    "primaryServicePoint": "be6cdc85-1202-4c48-99fa-56af591f5a3a",
    "servicePointIds": [
      "be6cdc85-1202-4c48-99fa-56af591f5a3a"
    ],
    "servicePoints": [],
    "metadata": {
      "createdDate": "2025-11-26T22:47:07.060+00:00",
      "createdByUserId": "daaf98f2-4d8b-4ebf-b473-31f8c449fdc2",
      "updatedDate": "2025-11-26T22:53:26.844+00:00",
      "updatedByUserId": "daaf98f2-4d8b-4ebf-b473-31f8c449fdc2"
    }
  },
  "type": "UPDATE",
  "tenant": "testTenant",
  "eventId": "ea61dfb6-b0c6-41d1-bede-4e013d3a9b47",
  "eventTs": 1764197606855
}

=== folio-org/mod-rtac-cache/src/test/resources/__files/kafka-events/create-library-event.json
{
  "new": {
    "id": "79f1cd00-09cc-4c9c-99c1-d8ad1b77d128",
    "name": "Old library name",
    "code": "Old library code",
    "campusId": "3cb95a54-1aac-47f2-9f97-c2b54a01bbfe",
    "metadata": {
      "createdDate": "2025-11-26T22:51:38.334+00:00",
      "createdByUserId": "daaf98f2-4d8b-4ebf-b473-31f8c449fdc2",
      "updatedDate": "2025-11-26T22:51:38.334+00:00",
      "updatedByUserId": "daaf98f2-4d8b-4ebf-b473-31f8c449fdc2"
    }
  },
  "type": "CREATE",
  "tenant": "testTenant",
  "eventId": "4f8920c5-9c10-4dea-85d7-887ac0451c67",
  "eventTs": 1764197498348
}

=== folio-org/mod-rtac-cache/src/test/resources/__files/kafka-events/update-instance-member-tenant-event.json
{
  "old": {
    "id": "843b368d-411c-4dce-bd64-99afc53f508d",
    "_version": 1,
    "hrid": "instiyey000000000001",
    "source": "FOLIO",
    "title": "ABA Journal",
    "alternativeTitles": [],
    "editions": [],
    "series": [],
    "identifiers": [
      {
        "value": "0747-0088",
        "identifierTypeId": "913300b2-03ed-469a-8179-c1092c991227"
      },
      {
        "value": "84641839",
        "identifierTypeId": "c858e4f2-2b6b-4385-842b-60732ee14abb"
      }
    ],
    "contributors": [],
    "subjects": [],
    "classifications": [],
    "publication": [
      {
        "publisher": "American Bar Association",
        "place": "Chicago, Ill.",
        "dateOfPublication": "1915-1983"
      }
    ],
    "publicationFrequency": [],
    "publicationRange": [],
    "electronicAccess": [],
    "instanceTypeId": "6312d172-f0cf-40f6-b27d-9fa8feaf332f",
    "instanceFormatIds": [],
    "instanceFormats": [],
    "physicalDescriptions": [],
    "languages": [],
    "notes": [],
    "administrativeNotes": [],
    "previouslyHeld": false,
    "discoverySuppress": false,
    "deleted": false,
    "statisticalCodeIds": [],
    "statusUpdatedDate": "2026-01-13T12:48:51.113+0000",
    "metadata": {
      "createdDate": "2026-01-13T12:48:51.113+00:00",
      "updatedDate": "2026-01-13T12:48:51.113+00:00"
    },
    "holdingsRecords2": [],
    "natureOfContentTermIds": [
      "0abeee3d-8ad2-4b04-92ff-221b4fce1075"
    ]
  },
  "new": {
    "id": "843b368d-411c-4dce-bd64-99afc53f508d",
    "_version": 2,
    "hrid": "instiyey000000000001",
    "source": "FOLIO",
    "title": "ABA Journal",
    "alternativeTitles": [],
    "editions": [],
    "series": [],
    "identifiers": [
      {
        "value": "0747-0088",
        "identifierTypeId": "913300b2-03ed-469a-8179-c1092c991227"
      },
      {
        "value": "84641839",
        "identifierTypeId": "c858e4f2-2b6b-4385-842b-60732ee14abb"
      }
    ],
    "contributors": [],
    "subjects": [],
    "classifications": [],
    "publication": [
      {
        "publisher": "American Bar Association",
        "place": "Chicago, Ill.",
        "dateOfPublication": "1915-1983"
      }
    ],
    "publicationFrequency": [],
    "publicationRange": [],
    "electronicAccess": [],
    "instanceTypeId": "6312d172-f0cf-40f6-b27d-9fa8feaf332f",
    "instanceFormatIds": [
      "549e3381-7d49-44f6-8232-37af1cb5ecf3"
    ],
    "instanceFormats": [],
    "physicalDescriptions": [],
    "languages": [],
    "notes": [],
    "administrativeNotes": [],
    "previouslyHeld": false,
    "staffSuppress": false,
    "discoverySuppress": false,
    "deleted": false,
    "statisticalCodeIds": [],
    "statusUpdatedDate": "2026-01-13T12:48:51.113+0000",
    "tags": {
      "tagList": []
    },
    "metadata": {
      "createdDate": "2026-01-13T12:48:51.113+00:00",
      "updatedDate": "2026-01-13T14:50:29.806+00:00",
      "updatedByUserId": "2a26cc94-9d20-454b-9c1b-57f6e7a63908"
    },
    "holdingsRecords2": [],
    "natureOfContentTermIds": [
      "0abeee3d-8ad2-4b04-92ff-221b4fce1075"
    ]
  },
  "type": "UPDATE",
  "tenant": "testTenant",
  "eventId": "98a4c396-6c75-4474-a5b5-1d8de0b29208",
  "eventTs": 1768315829846
}

=== folio-org/mod-rtac-cache/src/test/resources/__files/kafka-events/update-holdings-event.json
{
  "old": {
    "id": "55fa3746-8176-49c5-9809-b29dd7bb9b47",
    "_version": 3,
    "sourceId": "f32d531e-df79-46b3-8932-cdd35f7a2264",
    "hrid": "colho00000680893",
    "formerIds": [],
    "instanceId": "843b368d-411c-4dce-bd64-99afc53f508d",
    "permanentLocationId": "108ef496-ef5b-421b-baa9-109833493599",
    "effectiveLocationId": "108ef496-ef5b-421b-baa9-109833493599",
    "electronicAccess": [],
    "callNumber": "OLD-CALL-456",
    "administrativeNotes": [],
    "notes": [],
    "holdingsStatements": [],
    "holdingsStatementsForIndexes": [],
    "holdingsStatementsForSupplements": [],
    "discoverySuppress": false,
    "statisticalCodeIds": [],
    "metadata": {
      "createdDate": "2024-08-07T14:04:36.888+00:00",
      "createdByUserId": "9f9d1c46-52e1-4bb7-9c6c-56e6bb945c42",
      "updatedDate": "2025-06-02T08:31:22.688+00:00",
      "updatedByUserId": "daaf98f2-4d8b-4ebf-b473-31f8c449fdc2"
    }
  },
  "new": {
    "id": "55fa3746-8176-49c5-9809-b29dd7bb9b47",
    "version": 4,
    "sourceId": "f32d531e-df79-46b3-8932-cdd35f7a2264",
    "hrid": "oho00026200995",
    "formerIds": [],
    "instanceId": "843b368d-411c-4dce-bd64-99afc53f508d",
    "permanentLocationId": "2d65e095-5750-56ee-ca60-5584eg7ce39b",
    "effectiveLocationId": "2d65e095-5750-56ee-ca60-5584eg7ce39b",
    "electronicAccess": [],
    "callNumber": "NEW-CALL-456",
    "copyNumber": "Test",
    "administrativeNotes": [],
    "notes": [
      {
        "holdingsNoteTypeId": "de14ac4e-f705-404a-8027-4a69d9dc8075",
        "note": "Test",
        "staffOnly": false
      }
    ],
    "holdingsStatements": [
      {
        "statement": "Test",
        "note": "Test",
        "staffNote": "Test"
      }
    ],
    "holdingsStatementsForIndexes": [],
    "holdingsStatementsForSupplements": [],
    "discoverySuppress": false,
    "statisticalCodeIds": [],
    "metadata": {
      "createdDate": "2024-08-07T14:04:36.888+00:00",
      "createdByUserId": "9f9d1c46-52e1-4bb7-9c6c-56e6bb945c42",
      "updatedDate": "2025-11-03T16:19:30.969+00:00",
      "updatedByUserId": "daaf98f2-4d8b-4ebf-b473-31f8c449fdc2"
    }
  },
  "type": "UPDATE",
  "tenant": "testTenant",
  "eventId": "d05aca1c-e33c-45ee-b624-859a1ad91f35",
  "eventTs": 1762186771227
}

=== folio-org/mod-rtac-cache/src/test/resources/__files/kafka-events/create-bound-with-event.json
{
  "new": {
    "instanceId": "4b0559ef-6738-4d51-98fb-16db8cbf935e",
    "id": "6fc15a10-aab1-4726-9d5a-ee51cdf80606",
    "holdingsRecordId": "48525495-05b0-488e-a0c5-0f3ec5c7a0f2",
    "itemId": "522d41d3-0e04-416d-9f52-90ac67685a78",
    "metadata": {
      "createdDate": "2025-12-22T12:48:24.652+00:00",
      "updatedDate": "2025-12-22T12:48:24.652+00:00"
    }
  },
  "type": "CREATE",
  "tenant": "testTenant",
  "eventId": "4b6d1751-e4b7-4b58-bca4-faab359035f4",
  "eventTs": 1766407704686
}

=== folio-org/mod-rtac-cache/src/test/resources/__files/kafka-events/create-item-event.json
{
  "new": {
    "instanceId": "843b368d-411c-4dce-bd64-99afc53f508d",
    "id": "522d41d3-0e04-416d-9f52-90ac67685a78",
    "_version": 1,
    "hrid": "colit00001542562",
    "holdingsRecordId": "55fa3746-8176-49c5-9809-b29dd7bb9b47",
    "formerIds": [],
    "barcode": "1232323232",
    "itemLevelCallNumber": "NEW-CALL-456",
    "effectiveCallNumberComponents": {
      "callNumber": "NEW-CALL-456"
    },
    "yearCaption": [],
    "administrativeNotes": [],
    "notes": [],
    "circulationNotes": [],
    "status": {
      "name": "Checked out",
      "date": "2025-11-04T00:45:23.144+00:00"
    },
    "materialTypeId": "1a54b431-2e4f-452d-9cae-9cee66c9a892",
    "permanentLoanTypeId": "2b94c631-fca9-4892-a730-03ee529ffe27",
    "effectiveLocationId": "2d65e095-5750-56ee-ca60-5584eg7ce39b",
    "electronicAccess": [],
    "statisticalCodeIds": [],
    "tags": {
      "tagList": []
    },
    "metadata": {
      "createdDate": "2025-11-04T00:45:23.144+00:00",
      "createdByUserId": "daaf98f2-4d8b-4ebf-b473-31f8c449fdc2",
      "updatedDate": "2025-11-04T00:45:23.144+00:00",
      "updatedByUserId": "daaf98f2-4d8b-4ebf-b473-31f8c449fdc2"
    }
  },
  "type": "CREATE",
  "tenant": "testTenant",
  "eventId": "d05aca1c-e33c-45ee-b624-859a1ad91f35",
  "eventTs": 1762186771227
}

=== folio-org/mod-rtac-cache/src/test/resources/__files/kafka-events/create-holdings-event.json
{
  "new": {
    "id": "55fa3746-8176-49c5-9809-b29dd7bb9b47",
    "version": 4,
    "sourceId": "f32d531e-df79-46b3-8932-cdd35f7a2264",
    "hrid": "oho00026200995",
    "formerIds": [],
    "instanceId": "843b368d-411c-4dce-bd64-99afc53f508d",
    "permanentLocationId": "2d65e095-5750-56ee-ca60-5584eg7ce39b",
    "effectiveLocationId": "2d65e095-5750-56ee-ca60-5584eg7ce39b",
    "electronicAccess": [],
    "callNumber": "NEW-CALL-456",
    "copyNumber": "Test",
    "administrativeNotes": [],
    "notes": [
      {
        "holdingsNoteTypeId": "de14ac4e-f705-404a-8027-4a69d9dc8075",
        "note": "Test",
        "staffOnly": false
      }
    ],
    "holdingsStatements": [
      {
        "statement": "Test",
        "note": "Test",
        "staffNote": "Test"
      }
    ],
    "holdingsStatementsForIndexes": [],
    "holdingsStatementsForSupplements": [],
    "discoverySuppress": false,
    "statisticalCodeIds": [],
    "metadata": {
      "createdDate": "2024-08-07T14:04:36.888+00:00",
      "createdByUserId": "9f9d1c46-52e1-4bb7-9c6c-56e6bb945c42",
      "updatedDate": "2025-11-03T16:19:30.969+00:00",
      "updatedByUserId": "daaf98f2-4d8b-4ebf-b473-31f8c449fdc2"
    }
  },
  "type": "CREATE",
  "tenant": "testTenant",
  "eventId": "d05aca1c-e33c-45ee-b624-859a1ad91f35",
  "eventTs": 1762186771227
}

=== folio-org/mod-rtac-cache/src/test/resources/__files/kafka-events/delete-bound-with-event.json
{
  "old": {
    "instanceId": "843b368d-411c-4dce-bd64-99afc53f508d",
    "id": "6fc15a10-aab1-4726-9d5a-ee51cdf80606",
    "holdingsRecordId": "55fa3746-8176-49c5-9809-b29dd7bb9b47",
    "itemId": "522d41d3-0e04-416d-9f52-90ac67685a78",
    "metadata": {
      "createdDate": "2025-12-22T12:48:24.652+00:00",
      "updatedDate": "2025-12-22T12:48:24.652+00:00"
    }
  },
  "type": "DELETE",
  "tenant": "testTenant",
  "eventId": "4b6d1751-e4b7-4b58-bca4-faab359035f4",
  "eventTs": 1766407704686
}
