=== folio-org/mod-rtac-cache/src/main/resources/swagger.api/schemas/kafka/inventoryResourceEvent.json
{
  "type": "object",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Inventory event body",
  "properties": {
    "eventId": {
      "description": "Event id",
      "type": "string"
    },
    "type": {
      "description": "Event type",
      "$ref": "inventoryEventType.json"
    },
    "tenant": {
      "description": "Tenant id",
      "type": "string"
    },
    "eventTs": {
      "description": "Event timestamp",
      "type": "integer",
      "format": "int64"
    },
    "new": {
      "description": "Record new fields",
      "type": "object"
    },
    "old": {
      "description": "Record old fields",
      "type": "object"
    }
  }
}

=== folio-org/mod-rtac-cache/src/test/resources/__files/kafka-events/update-library-event.json
{
  "old": {
    "id": "79f1cd00-09cc-4c9c-99c1-d8ad1b77d128",
    "name": "Old library name",
    "code": "Old library code",
    "campusId": "3cb95a54-1aac-47f2-9f97-c2b54a01bbfe",
    "metadata": {
      "createdDate": "2025-11-26T22:51:38.334+00:00",
      "createdByUserId": "daaf98f2-4d8b-4ebf-b473-31f8c449fdc2",
      "updatedDate": "2025-11-26T22:51:38.334+00:00",
      "updatedByUserId": "daaf98f2-4d8b-4ebf-b473-31f8c449fdc2"
    }
  },
  "new": {
    "id": "79f1cd00-09cc-4c9c-99c1-d8ad1b77d128",
    "name": "New library name",
    "code": "New library code",
    "campusId": "3cb95a54-1aac-47f2-9f97-c2b54a01bbfe",
    "metadata": {
      "createdDate": "2025-11-26T22:51:38.334+00:00",
      "createdByUserId": "daaf98f2-4d8b-4ebf-b473-31f8c449fdc2",
      "updatedDate": "2025-11-26T23:21:52.250+00:00",
      "updatedByUserId": "daaf98f2-4d8b-4ebf-b473-31f8c449fdc2"
    }
  },
  "type": "UPDATE",
  "tenant": "testTenant",
  "eventId": "783ed91c-b949-496b-9c51-b2616fe22f2a",
  "eventTs": 1764199312262
}

=== folio-org/mod-rtac-cache/src/test/resources/__files/kafka-events/delete-library-event.json
{
  "old": {
    "id": "79f1cd00-09cc-4c9c-99c1-d8ad1b77d128",
    "name": "New library name",
    "code": "New library code",
    "campusId": "3cb95a54-1aac-47f2-9f97-c2b54a01bbfe",
    "metadata": {
      "createdDate": "2025-11-26T22:51:38.334+00:00",
      "createdByUserId": "daaf98f2-4d8b-4ebf-b473-31f8c449fdc2",
      "updatedDate": "2025-11-26T23:21:52.250+00:00",
      "updatedByUserId": "daaf98f2-4d8b-4ebf-b473-31f8c449fdc2"
    }
  },
  "type": "DELETE",
  "tenant": "testTenant",
  "eventId": "bf32a249-6dce-44cb-98a0-80709516b062",
  "eventTs": 1764199418754
}

=== folio-org/mod-rtac-cache/src/test/resources/__files/kafka-events/update-material-type-event.json
{
  "old": {
    "id": "1a54b431-2e4f-452d-9cae-9cee66c9a892",
    "name": "book",
    "source": "consortium"
  },
  "new": {
    "id": "1a54b431-2e4f-452d-9cae-9cee66c9a892",
    "name": "book updated",
    "source": "consortium"
  },
  "type": "UPDATE",
  "tenant": "testTenant",
  "eventId": "2fbc3ab5-6ff3-4d82-816b-6c687727f166",
  "eventTs": 1764745002000
}

=== folio-org/mod-rtac-cache/src/test/resources/__files/kafka-events/update-loan-type-event.json
{
  "old": {
    "id": "2b94c631-fca9-4892-a730-03ee529ffe27",
    "name": "Can circulate",
    "source": "consortium"
  },
  "new": {
    "id": "2b94c631-fca9-4892-a730-03ee529ffe27",
    "name": "Can circulate updated",
    "source": "consortium"
  },
  "type": "UPDATE",
  "tenant": "testTenant",
  "eventId": "a95d5921-5ea3-4de3-95f2-d665126fc97d",
  "eventTs": 1764745004000
}

=== folio-org/mod-rtac-cache/src/test/resources/__files/kafka-events/update-holdings-move-to-cached-instance-event.json
{
  "old": {
    "id": "55fa3746-8176-49c5-9809-b29dd7bb9b47",
    "_version": 3,
    "sourceId": "f32d531e-df79-46b3-8932-cdd35f7a2264",
    "hrid": "colho00000680893",
    "formerIds": [],
    "instanceId": "843b368d-411c-4dce-bd64-99afc53f508d",
    "permanentLocationId": "108ef496-ef5b-421b-baa9-109833493599",
    "effectiveLocationId": "108ef496-ef5b-421b-baa9-109833493599",
    "electronicAccess": [],
    "callNumber": "OLD-CALL-456",
    "administrativeNotes": [],
    "notes": [],
    "holdingsStatements": [],
    "holdingsStatementsForIndexes": [],
    "holdingsStatementsForSupplements": [],
    "discoverySuppress": false,
    "statisticalCodeIds": []
  },
  "new": {
    "id": "55fa3746-8176-49c5-9809-b29dd7bb9b47",
    "version": 4,
    "sourceId": "f32d531e-df79-46b3-8932-cdd35f7a2264",
    "hrid": "oho00026200995",
    "formerIds": [],
    "instanceId": "4b0559ef-6738-4d51-98fb-16db8cbf935e",
    "permanentLocationId": "2d65e095-5750-56ee-ca60-5584eg7ce39b",
    "effectiveLocationId": "2d65e095-5750-56ee-ca60-5584eg7ce39b",
    "electronicAccess": [],
    "callNumber": "NEW-CALL-456",
    "copyNumber": "Test",
    "administrativeNotes": [],
    "notes": [
      {
        "holdingsNoteTypeId": "de14ac4e-f705-404a-8027-4a69d9dc8075",
        "note": "Test",
        "staffOnly": false
      }
    ],
    "holdingsStatements": [
      {
        "statement": "Test",
        "note": "Test",
        "staffNote": "Test"
      }
    ],
    "holdingsStatementsForIndexes": [],
    "holdingsStatementsForSupplements": [],
    "discoverySuppress": false,
    "statisticalCodeIds": []
  },
  "type": "UPDATE",
  "tenant": "testTenant",
  "eventId": "d05aca1c-e33c-45ee-b624-859a1ad91f35",
  "eventTs": 1762186771227
}

=== folio-org/mod-rtac-cache/src/test/resources/__files/kafka-events/update-item-move-to-another-holding-event.json
{
  "old": {
    "instanceId": "843b368d-411c-4dce-bd64-99afc53f508d",
    "id": "522d41d3-0e04-416d-9f52-90ac67685a78",
    "_version": 1,
    "hrid": "colit00001542562",
    "holdingsRecordId": "55fa3746-8176-49c5-9809-b29dd7bb9b47",
    "formerIds": [],
    "itemLevelCallNumber": "NEW-CALL-456",
    "effectiveCallNumberComponents": {
      "callNumber": "NEW-CALL-456"
    },
    "yearCaption": [],
    "administrativeNotes": [],
    "notes": [],
    "circulationNotes": [],
    "status": {
      "name": "Available",
      "date": "2025-11-04T00:45:23.144+00:00"
    },
    "permanentLoanTypeId": "2b94c631-fca9-4892-a730-03ee529ffe27",
    "effectiveLocationId": "2d65e095-5750-56ee-ca60-5584eg7ce39b",
    "electronicAccess": [],
    "statisticalCodeIds": [],
    "tags": {
      "tagList": []
    }
  },
  "new": {
    "instanceId": "843b368d-411c-4dce-bd64-99afc53f508d",
    "id": "522d41d3-0e04-416d-9f52-90ac67685a78",
    "_version": 2,
    "hrid": "colit00001542562",
    "holdingsRecordId": "48525495-05b0-488e-a0c5-0f3ec5c7a0f2",
    "formerIds": [],
    "barcode": "1232323232",
    "itemLevelCallNumber": "NEW-CALL-456",
    "effectiveCallNumberComponents": {
      "callNumber": "NEW-CALL-456"
    },
    "yearCaption": [],
    "administrativeNotes": [],
    "notes": [],
    "circulationNotes": [],
    "status": {
      "name": "Checked out",
      "date": "2025-11-04T00:45:23.144+00:00"
    },
    "materialTypeId": "1a54b431-2e4f-452d-9cae-9cee66c9a892",
    "permanentLoanTypeId": "2b94c631-fca9-4892-a730-03ee529ffe27",
    "effectiveLocationId": "2d65e095-5750-56ee-ca60-5584eg7ce39b",
    "electronicAccess": [],
    "statisticalCodeIds": [],
    "tags": {
      "tagList": []
    }
  },
  "type": "UPDATE",
  "tenant": "testTenant",
  "eventId": "d05aca1c-e33c-45ee-b624-859a1ad91f36",
  "eventTs": 1762186771228
}

=== folio-org/mod-rtac-cache/src/test/resources/__files/kafka-events/delete-item-event.json
{
  "old": {
    "instanceId": "843b368d-411c-4dce-bd64-99afc53f508d",
    "id": "522d41d3-0e04-416d-9f52-90ac67685a78",
    "_version": 1,
    "hrid": "colit00001542562",
    "holdingsRecordId": "55fa3746-8176-49c5-9809-b29dd7bb9b47",
    "formerIds": [],
    "itemLevelCallNumber": "NEW-CALL-456",
    "effectiveCallNumberComponents": {},
    "yearCaption": [],
    "administrativeNotes": [],
    "notes": [],
    "circulationNotes": [],
    "status": {
      "name": "Available",
      "date": "2025-11-04T00:45:23.144+00:00"
    },
    "permanentLoanTypeId": "2b94c631-fca9-4892-a730-03ee529ffe27",
    "effectiveLocationId": "2d65e095-5750-56ee-ca60-5584eg7ce39b",
    "electronicAccess": [],
    "statisticalCodeIds": [],
    "tags": {
      "tagList": []
    },
    "metadata": {
      "createdDate": "2025-11-04T00:45:23.144+00:00",
      "createdByUserId": "daaf98f2-4d8b-4ebf-b473-31f8c449fdc2",
      "updatedDate": "2025-11-04T00:45:23.144+00:00",
      "updatedByUserId": "daaf98f2-4d8b-4ebf-b473-31f8c449fdc2"
    }
  },
  "type": "DELETE",
  "tenant": "testTenant",
  "eventId": "d05aca1c-e33c-45ee-b624-859a1ad91f35",
  "eventTs": 1762186771227
}

=== folio-org/mod-rtac-cache/src/test/resources/__files/kafka-events/delete-location-event.json
{
  "old": {
    "id": "1c54d084-4639-45dd-b9c9-4473df6bd28a",
    "name": "New location name",
    "code": "New location code",
    "discoveryDisplayName": "New location name",
    "isActive": true,
    "institutionId": "6ecd8132-caef-4f87-bbb0-9fc07d71357d",
    "campusId": "3cb95a54-1aac-47f2-9f97-c2b54a01bbfe",
    "libraryId": "79f1cd00-09cc-4c9c-99c1-d8ad1b77d128",
    "details": {},
    "primaryServicePoint": "be6cdc85-1202-4c48-99fa-56af591f5a3a",
    "servicePointIds": [
      "be6cdc85-1202-4c48-99fa-56af591f5a3a"
    ],
    "servicePoints": [],
    "metadata": {
      "createdDate": "2025-11-26T22:47:07.060+00:00",
      "createdByUserId": "daaf98f2-4d8b-4ebf-b473-31f8c449fdc2",
      "updatedDate": "2025-11-26T22:53:26.844+00:00",
      "updatedByUserId": "daaf98f2-4d8b-4ebf-b473-31f8c449fdc2"
    }
  },
  "type": "DELETE",
  "tenant": "testTenant",
  "eventId": "471b914b-a44b-4f75-994b-0933eb9cfac9",
  "eventTs": 1764199412111
}
