=== folio-org/mod-rtac-cache/src/main/resources/swagger.api/schemas/kafka/pieceResourceEvent.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Piece resource event",
  "type": "object",
  "properties": {
    "id": {
      "description": "UUID of the event",
      "type": "string"
    },
    "action": {
      "description": "Action performed on the piece",
      "$ref": "pieceEventAction.json"
    },
    "pieceId": {
      "description": "UUID of the piece",
      "type": "string"
    },
    "userId": {
      "description": "UUID of the user who performed the action",
      "type": "string"
    },
    "eventDate": {
      "description": "Date time when event triggered",
      "format": "date-time",
      "type": "string"
    },
    "actionDate": {
      "description": "Date time when piece action occurred",
      "format": "date-time",
      "type": "string"
    },
    "pieceSnapshot": {
      "description": "Snapshot of the piece at the time of the event",
      "$ref": "../orders/piece.json"
    }
  },
  "additionalProperties": false
}

=== folio-org/mod-rtac-cache/src/test/resources/__files/kafka-events/create-piece-event.json
{
  "id": "9085d5a7-17b1-4fbb-9a53-c42f386b02fd",
  "action": "Create",
  "pieceId": "d892d70b-96be-4e5b-ab11-05839eb5df40",
  "userId": "daaf98f2-4d8b-4ebf-b473-31f8c449fdc2",
  "eventDate": "2025-11-13T11:47:42.866+00:00",
  "actionDate": "2025-11-13T11:47:42.829+00:00",
  "pieceSnapshot": {
    "id": "d892d70b-96be-4e5b-ab11-05839eb5df40",
    "format": "Physical",
    "itemId": "522d41d3-0e04-416d-9f52-90ac67685a78",
    "poLineId": "a22efa99-4f2d-43d1-9c3e-0d98be3205eb",
    "titleId": "b7aa8e9c-db80-4c6b-8e84-c85c6f10ff53",
    "holdingId": "55fa3746-8176-49c5-9809-b29dd7bb9b47",
    "displayOnHolding": true,
    "displayToPublic": true,
    "receivingStatus": "Expected",
    "isBound": false
  }
}
